#!/usr/bin/env bash

# Create k3d cluster if not exists
if ! k3d cluster list | grep -q '^k3s-default'; then
  echo "[INFO] Creating k3d cluster..."
  k3d cluster create k3s-default --port 8888:80@loadbalancer
else
  echo "[INFO] k3d cluster already exists."
fi


# remove the KUBECONFIG from bash and zsh if present because that is for k3s not k3d
# if grep -q 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' ~/.zshrc; then
#   sed -i '/export KUBECONFIG=\/etc\/rancher\/k3s\/k3s.yaml/d' ~/.zshrc
# fi
if grep -q 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' ~/.bashrc; then
  sed -i '/export KUBECONFIG=\/etc\/rancher\/k3s\/k3s.yaml/d' ~/.bashrc
fi

# Set KUBECONFIG to k3d's config
# export KUBECONFIG=$(k3d kubeconfig write k3s-default) # will not work here
echo "alias k='kubectl'" >> ~/.bashrc

echo "K3d cluster created and KUBECONFIG set!"
kubectl create namespace argocd || true
kubectl create namespace dev || true

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

kubectl apply -f k8s/dev/